CapaPresentacionAdmind/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using System.string;

using CapaEntidad;
using CapaNegocio;
//using ClosedXML.Excel;

namespace CapaPresentacionAdmind.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }
        [HttpGet]
        public JsonResult ListarUsuarios()
        {
            List<Usuario> oLista = new List<Usuario>();

            oLista = new CN_Usuarios().Listar();

            return Json(new { data = oLista } , JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarUsuario(Usuario objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if(objeto.IdUsuario == 0)
            {
                resultado = new CN_Usuarios().Registrar(objeto, out mensaje);

            } else
            {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

    }
}

CapaPresentacionAdmind/Controllers/MantenedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmind.Controllers
{
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }

        public ActionResult Marca()
        {
            return View();
        }

        public ActionResult Producto()
        {
            return View();
        }
    }
}

CapaPresentacionAdmind/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CapaPresentacionAdmind/Views/Home/Usuarios.cshtml
@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Usuarios</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"> </i> Lista de Usuarios
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-primary" onclick="abrirModal(null)">Crear nuevo</button>
            </div>
        </div>
        <hr />
        <table id="TablaUsuarios" class="display cell-border" style="width: 100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Correo</th>
                    <th>Activo</th>
                    <th></th>
                </tr>


            </thead>
            <tbody>
            </tbody>

        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Usuario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- guardamos el nuevo usuario creado (sin activar) -->
                <input id="txtid" type="text" value="0" />

                <div class="row g-2">


                    <div class="col-sm-6">
                        <label for="txtnombres" class="form-label">Nombres</label>
                        <input type="text" class="form-control" id="txtnombres" autocomplete="off">
                    </div>


                    <div class="col-sm-6">
                        <label for="txtapellidos" class="form-label">Apellidos</label>
                        <input type="text" class="form-control" id="txtapellidos" autocomplete="off">
                    </div>


                    <div class="col-sm-6">
                        <label for="txtcorreo" class="form-label">Correo</label>
                        <input type="email" class="form-control" id="txtcorreo" placeholder="name@example.com" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">

                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>

                </div>

                <div class="row mt-4">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
                </div>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $("#TablaUsuarios").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("listarUsuarios", "Home")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "Nombre" },
                { "data": "Apellidos" },
                { "data": "Correo" },
                {
                    "data": "Activo", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge text-bg-success">Si</span>'
                        } else {
                            return '<span class="badge text-bg-secondary">No</span>'
                        }
                    }

                },
                {

                    "defaultContent": '<div class="text-center">' +
                        '<button type="button" class="btn btn-primary btn-sm btn-editar mx-auto"> <i class="fas fa-pen me-1"> </i></button> ' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 mx-auto"> <i class="fas fa-trash me-1"> </i></button>' +
                        '</div>',


                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }
            ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/2.0.2/i18n/es-ES.json"
            }
        });

        function abrirModal(json) {

            $("#txtid").val(0);
            $("#txtnombres").val("");
            $("#txtapellidos").val("");
            $("#txtcorreo").val("");
            $("#cboactivo").val(1);

            $("#mensajeError").hide();

            if (json != null) {

                $("#txtid").val(json.IdUsuario);
                $("#txtnombres").val(json.Nombre);
                $("#txtapellidos").val(json.Apellidos);
                $("#txtcorreo").val(json.Correo);
                $("#cboactivo").val(json.Activo == true ? 1 : 0);

            }

            $("#FormModal").modal("show");
        }

        $("#TablaUsuarios tbody").on("click", '.btn-editar', function () {

            FilaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(FilaSeleccionada).data();

           // console.log(data)

           abrirModal(data)


        })


        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var usuarioseleccionado = $(this).closest("tr");

            var data = tabladata.row(usuarioseleccionado).data();


            swal({
                title: "Esta Seguro?",
                text: "¿Desea eliminar el usuario?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
            function () {

                 jQuery.ajax({
                    url: '@Url.Action("EliminarUsuario", "Home")',
                    type: "POST",
                     data: JSON.stringify({ id: data.IdUsuario }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {

                        debugger;

                        if (data.resultado) {

                            tabladata.row(usuarioseleccionado).remove().draw();
                        } else {

                            swal("No se pudo eliminar", data.mensaje, "error")
                        }
                    },
                    error: function (error) {
                        console.log(error)
                    }
                 });

                });


            console.log(data);

        })

        function Guardar() {

            var Usuario = {

                IdUsuario: $("#txtid").val(),
                Activo: $("#cboactivo").val() == 1 ? true : false,
                Apellidos: $("#txtapellidos").val(),
                Correo: $("#txtcorreo").val(),
                Nombre: $("#txtnombres").val(),

            }

            jQuery.ajax({
                url: '@Url.Action("GuardarUsuario", "Home")',
                type: "POST",
                data: JSON.stringify({ objeto : Usuario}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
               success: function (data) {

                  // $(".modal-body").LoadingOverlay("hide");
                  // debugger;

                    //USUARIO NUEVO
                   if (Usuario.IdUsuario == 0) {

                       if (data.resultado != 0) {

                           Usuario.IdUsuario = data.resultado;
                           tabladata.row.add(Usuario).draw(false);
                           $("#FormModal").modal("hide");

                       } else {
                           $("#mensajeError").text(data.mensaje);
                           $("#mensajeError").show();
                           //  alert(data.mensaje)

                       }
                   }
                         //USUARIO EDITAR
                    else {

                        if (data.resultado) {

                            tabladata.row(filaSeleccionada).data(Usuario).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                    error: function (error) {
                        console.log(error)
                    },
                    beforeSend: function () {

                    }

                });
            }


    </script>

}

CapaPresentacionAdmind/Views/Mantenedor/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categoria</h2>

CapaPresentacionAdmind/Views/Mantenedor/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marca</h2>

CapaPresentacionAdmind/Views/Mantenedor/Producto.cshtml
@{
    ViewBag.Title = "Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Producto</h2>

CapaPresentacionAdmind/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand (titulo)-->
        <a class="navbar-brand ps-3" href="index.html">MI TIENDA</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!--<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo del usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Informacion
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Categoria","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-list-ul"></i></div>
                            Categoria
                        </a>
                        <a class="nav-link" href="@Url.Action("Marca","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-barcode"></i></div>
                            Marca
                        </a>
                        <a class="nav-link" href="@Url.Action("Producto","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                            Producto
                        </a>

                        @*<div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Productos
                        </a>*@
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <ul class="nav navbar-nav">
                        @RenderBody()
                    </ul>

                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @*  <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li> *@



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/Complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>